# Default values for tensorio-bundler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rest:
  replicaCount: 1
  image:
    repository: docai/tensorio-bundler
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  deployment:
    repository: https://repository.tensorio-models.doc.ai/rest/v1/repository
    # TODO: Use a secret here
    repositoryApiKey: lol
secret:
  name: tensorio-bundler
  sacredKey: sacred.json
  botUserAccessTokenKey: bot-user-access-token
